# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 856ecc7f00959b6dabc7f69693ae5b9c06669749b5147fb17392671b83aafce97e3fb854309afe594c326091afeb6aba72ff88123a8353d8e05c12617f559947

test:
  secret_key_base: a8f58176579f73ab513b28b06cc55ce35c2b4983eebb22618bcd79ec75e508d009e0a5d28634c9a11985e88ac7141b82c3de8f0f607b657d47e7b5f66f95eba6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
